from korbinian.uniprot.parse.nonred import convert_uniprot_list_to_nonred_ff_via_uniref
from korbinian.uniprot.parse.retrieve import parse_large_flatfile_with_list_uniprot_accessions
from korbinian.uniprot.parse.retrieve import retrieve_uniprot_data_for_acc_list_in_xlsx_file
from korbinian.uniprot.parse.parse import create_csv_from_uniprot_flatfile
