from korbinian.old.TMD_cons import OLD_calculate_TMD_conservation
from korbinian.old.TMD_cons_gap_ID import OLD_calculate_TMD_conservation_by_gappedIdentity
from korbinian.old.sim_ratios import OLD_conduct_statistical_analysis_of_sim_ratios_saved_in_dfout05_simapcsv, OLD_fix_dfout05_simapcsv_by_adding_query_md5