from korbinian.cons_ratio.multiplelists.multiplelists import compare_rel_con_lists
from korbinian.cons_ratio.multipleproteins.multipleproteins import save_figures_describing_proteins_in_list
from korbinian.cons_ratio.singleprotein.SiPr_AAIMON_hist import save_hist_AAIMON_ratio_single_protein
from korbinian.cons_ratio.singleprotein.singleprotein import slice_homologues_and_count_gaps, calc_AAIMON
from korbinian.cons_ratio.singleprotein.nonTMD import calc_nonTMD_perc_ident_and_gaps